# Generated by Django 4.2.16 on 2025-01-17 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firefighter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('rank', models.CharField(max_length=50)),
                ('age', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Firetruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side_number', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=100)),
                ('prod_date', models.PositiveIntegerField()),
                ('seats', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Psi_Patrol.firetruck')),
            ],
        ),
        migrations.CreateModel(
            name='FirefighterInSquad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('firefighter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Psi_Patrol.firefighter')),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Psi_Patrol.squad')),
            ],
            options={
                'unique_together': {('squad', 'firefighter')},
            },
        ),
    ]
